### ISSUE TITLE
Prevent overlapping bookings

### ISSUE THREAD

**Issue by albronca** [kmigueis1/SkiBnb#2]
I was able to book the same place with the same dates twice. Shouldn't be doable

**Comment by kmigueis1** [comment]
Is it ok If i leave it such that you can book something in the past? Thats the only way to demonstrate the review functionality of the site since you can only review past bookings (otherwise you would have to book a place and wait like a month before you can review something)

**Comment by kmigueis1** [comment]
The booking widget will no longer create a booking if the user's existing bookings have conflicting dates.
